export const STRUCTURE_FIELDS = {
  divisions: {
    title: "Pridėkite naują padalinį",
    nameLabel: "Padalinio pavadinimas:",
    namePlaceholder: "Įveskite padalinio pavadinimą...",
    parentLabel: "Pasirinkite ofisus:",
    parentType: "offices",
    linkTable: "offices_divisions",
    linkFields: { parent: "office_id", child: "division_id" },
    successMessage: "Padalinys sukurtas sėkmingai",
    errorMessage: "Klaida kuriant padalinį. Bandykite dar kartą.",
    parentErrorMessage: "Pasirinkite bent vieną ofisą",
    parentCountText: (count: number) => `Pasirinkta: ${count} ofisas(-ai)`,
    actionText: "padalinį",
  },
  departments: {
    title: "Pridėkite naują skyrių",
    nameLabel: "Skyriaus pavadinimas:",
    namePlaceholder: "Įveskite skyriaus pavadinimą...",
    parentLabel: "Pasirinkite padalinius:",
    parentType: "divisions",
    linkTable: "divisions_departments",
    linkFields: { parent: "division_id", child: "department_id" },
    successMessage: "Skyrius sukurtas sėkmingai",
    errorMessage: "Klaida kuriant skyrių. Bandykite dar kartą.",
    parentErrorMessage: "Pasirinkite bent vieną padalinį",
    parentCountText: (count: number) => `Pasirinkta: ${count} padalinys(-iai)`,
    actionText: "skyrių",
  },
  groups: {
    title: "Pridėkite naują grupę",
    nameLabel: "Grupės pavadinimas:",
    namePlaceholder: "Įveskite grupės pavadinimą...",
    parentLabel: "Pasirinkite skyrius:",
    parentType: "departments",
    linkTable: "departments_groups",
    linkFields: { parent: "department_id", child: "group_id" },
    successMessage: "Grupė sukurta sėkmingai",
    errorMessage: "Klaida kuriant grupę. Bandykite dar kartą.",
    parentErrorMessage: "Pasirinkite bent vieną skyrių",
    parentCountText: (count: number) => `Pasirinkta: ${count} skyrius(-iai)`,
    actionText: "grupę",
  },
} as const;
